# Inicializacija Great Expectations

In [2]:
import great_expectations as gx

context = gx.get_context()

In [4]:
datasource_name = "energy_prices"

datasource = context.sources.add_pandas_filesystem(
    name=datasource_name,
    base_directory="../data"
)

In [5]:
data_asset_name = "energy_prices_data"

data_asset = datasource.add_csv_asset(
    name=data_asset_name,
    batching_regex=r"processed/electricity/prices/.*\.csv"
)

In [6]:
expectation_suite_name = "energy_prices_suite"

expectation_suite = context.add_or_update_expectation_suite(
    expectation_suite_name=expectation_suite_name
)

In [7]:
asset = context.get_datasource(
    datasource_name
).get_asset(
    data_asset_name
)

batch_request = asset.build_batch_request()

validator = context.get_validator(
    batch_request=batch_request,
    expectation_suite_name=expectation_suite_name
)

In [8]:
validator.head()

Calculating Metrics:   0%|          | 0/1 [00:00<?, ?it/s]

,datetime_utc,price,price.1,hour,day_of_week,day,month,year,is_weekend
0,2024-01-01 00:00:00+00:00,0.01,NaN,0,0,1,1,2024,False
1,2024-01-01 01:00:00+00:00,0.05,NaN,1,0,1,1,2024,False
2,2024-01-01 02:00:00+00:00,0.01,NaN,2,0,1,1,2024,False
3,2024-01-01 05:00:00+00:00,0.04,NaN,5,0,1,1,2024,False
4,2024-01-01 06:00:00+00:00,0.01,NaN,6,0,1,1,2024,False

In [9]:
data_asset_name = "energy_prices_by_zone"

data_asset = datasource.add_csv_asset(
    name=data_asset_name,
    batching_regex=r"processed/electricity/prices/(?P<zone>[^/]+)\.csv"
)

In [10]:
batches = data_asset.get_batch_list_from_batch_request(
    data_asset.build_batch_request()
)

len(batches)

37

In [11]:
batches

[Batch(datasource=PandasFilesystemDatasource(type='pandas_filesystem', name='energy_prices', id=None, assets=[CSVAsset(name='energy_prices_data', type='csv', id=None, order_by=[], batch_metadata={}, batching_regex=re.compile('processed/electricity/prices/.*\\.csv'), connect_options={}, splitter=None, sep=None, delimiter=None, header='infer', names=None, index_col=None, usecols=None, dtype=None, engine=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, skipfooter=0, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=None, skip_blank_lines=True, parse_dates=None, infer_datetime_format=None, keep_date_col=None, date_format=None, dayfirst=False, cache_dates=True, iterator=False, chunksize=None, compression='infer', thousands=None, decimal='.', lineterminator=None, quotechar='"', quoting=0, doublequote=True, escapechar=None, comment=None, encoding=None, encoding_errors='strict', dialect=None, on_bad_lines='error', delim_whitespace=None, low_memory=True, memory_map=False, float_precision=None, storage_options=None, dtype_backend=None), CSVAsset(name='energy_prices_by_zone', type='csv', id=None, order_by=[], batch_metadata={}, batching_regex=re.compile('processed/electricity/prices/(?P<zone>[^/]+)\\.csv'), connect_options={}, splitter=None, sep=None, delimiter=None, header='infer', names=None, index_col=None, usecols=None, dtype=None, engine=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, skipfooter=0, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=None, skip_blank_lines=True, parse_dates=None, infer_datetime_format=None, keep_date_col=None, date_format=None, dayfirst=False, cache_dates=True, iterator=False, chunksize=None, compression='infer', thousands=None, decimal='.', lineterminator=None, quotechar='"', quoting=0, doublequote=True, escapechar=None, comment=None, encoding=None, encoding_errors='strict', dialect=None, on_bad_lines='error', delim_whitespace=None, low_memory=True, memory_map=False, float_precision=None, storage_options=None, dtype_backend=None)], base_directory=PosixPath('../data'), data_context_root_directory=None), data_asset=CSVAsset(name='energy_prices_by_zone', type='csv', id=None, order_by=[], batch_metadata={}, batching_regex=re.compile('processed/electricity/prices/(?P<zone>[^/]+)\\.csv'), connect_options={}, splitter=None, sep=None, delimiter=None, header='infer', names=None, index_col=None, usecols=None, dtype=None, engine=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, skipfooter=0, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=None, skip_blank_lines=True, parse_dates=None, infer_datetime_format=None, keep_date_col=None, date_format=None, dayfirst=False, cache_dates=True, iterator=False, chunksize=None, compression='infer', thousands=None, decimal='.', lineterminator=None, quotechar='"', quoting=0, doublequote=True, escapechar=None, comment=None, encoding=None, encoding_errors='strict', dialect=None, on_bad_lines='error', delim_whitespace=None, low_memory=True, memory_map=False, float_precision=None, storage_options=None, dtype_backend=None), batch_request=BatchRequest(datasource_name='energy_prices', data_asset_name='energy_prices_by_zone', options={'path': 'processed/electricity/prices/AT.csv', 'zone': 'AT'}), data=<great_expectations.execution_engine.pandas_batch_data.PandasBatchData object at 0x7fc7cebb8860>, id='energy_prices-energy_prices_by_zone-zone_AT', metadata={'path': 'processed/electricity/prices/AT.csv', 'zone': 'AT'}, batch_markers={'ge_load_time': '20260817T173818.086458Z', 'pandas_data_fingerprint': '33059e94012c599e121ff4fc3adc000e'}, batch_spec={'path': '../data/processed/electricity/prices/AT.csv', 'reader_method': 'read_csv', 'reader_options': {}}, batch_definition={'datasource_name': 'energy_prices', 'data_connector_name': 'fluent', 'data_asset_name': 'energy_prices_by_zone', 'batch_identifiers': {'path': 'processed/electricity/prices/AT.csv', 'zone': 'AT'}}),
 Batch(datasource=PandasFilesystemDatasource(type='pandas_filesystem', name='energy_prices', id=None, assets=[CSVAsset(name='energy_prices_data', type='csv', id=None, order_by=[], batch_metadata={}, batching_regex=re.compile('processed/electricity/prices/.*\\.csv'), connect_options={}, splitter=None, sep=None, delimiter=None, header='infer', names=None, index_col=None, usecols=None, dtype=None, engine=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, skipfooter=0, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=None, skip_blank_lines=True, parse_dates=None, infer_datetime_format=None, keep_date_col=None, date_format=None, dayfirst=False, cache_dates=True, iterator=False, chunksize=None, compression='infer', thousands=None, decimal='.', lineterminator=None, quotechar='"', quoting=0, doublequote=True, escapechar=None, comment=None, encoding=None, encoding_errors='strict', dialect=None, on_bad_lines='error', delim_whitespace=None, low_memory=True, memory_map=False, float_precision=None, storage_options=None, dtype_backend=None), CSVAsset(name='energy_prices_by_zone', type='csv', id=None, order_by=[], batch_metadata={}, batching_regex=re.compile('processed/electricity/prices/(?P<zone>[^/]+)\\.csv'), connect_options={}, splitter=None, sep=None, delimiter=None, header='infer', names=None, index_col=None, usecols=None, dtype=None, engine=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, skipfooter=0, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=None, skip_blank_lines=True, parse_dates=None, infer_datetime_format=None, keep_date_col=None, date_format=None, dayfirst=False, cache_dates=True, iterator=False, chunksize=None, compression='infer', thousands=None, decimal='.', lineterminator=None, quotechar='"', quoting=0, doublequote=True, escapechar=None, comment=None, encoding=None, encoding_errors='strict', dialect=None, on_bad_lines='error', delim_whitespace=None, low_memory=True, memory_map=False, float_precision=None, storage_options=None, dtype_backend=None)], base_directory=PosixPath('../data'), data_context_root_directory=None), data_asset=CSVAsset(name='energy_prices_by_zone', type='csv', id=None, order_by=[], batch_metadata={}, batching_regex=re.compile('processed/electricity/prices/(?P<zone>[^/]+)\\.csv'), connect_options={}, splitter=None, sep=None, delimiter=None, header='infer', names=None, index_col=None, usecols=None, dtype=None, engine=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, skipfooter=0, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=None, skip_blank_lines=True, parse_dates=None, infer_datetime_format=None, keep_date_col=None, date_format=None, dayfirst=False, cache_dates=True, iterator=False, chunksize=None, compression='infer', thousands=None, decimal='.', lineterminator=None, quotechar='"', quoting=0, doublequote=True, escapechar=None, comment=None, encoding=None, encoding_errors='strict', dialect=None, on_bad_lines='error', delim_whitespace=None, low_memory=True, memory_map=False, float_precision=None, storage_options=None, dtype_backend=None), batch_request=BatchRequest(datasource_name='energy_prices', data_asset_name='energy_prices_by_zone', options={'path': 'processed/electricity/prices/BE.csv', 'zone': 'BE'}), data=<great_expectations.execution_engine.pandas_batch_data.PandasBatchData object at 0x7fc7ce485820>, id='energy_prices-energy_prices_by_zone-zone_BE', metadata={'path': 'processed/electricity/prices/BE.csv', 'zone': 'BE'}, batch_markers={'ge_load_time': '20260817T173818.128650Z', 'pandas_data_fingerprint': '39de5076cd73009e1de87592b1781086'}, batch_spec={'path': '../data/processed/electricity/prices/BE.csv', 'reader_method': 'read_csv', 'reader_options': {}}, batch_definition={'datasource_name': 'energy_prices', 'data_connector_name': 'fluent', 'data_asset_name': 'energy_prices_by_zone', 'batch_identifiers': {'path': 'processed/electricity/prices/BE.csv', 'zone': 'BE'}}),
 Batch(datasource=PandasFilesystemDatasource(type='pandas_filesystem', name='energy_prices', id=None, assets=[CSVAsset(name='energy_prices_data', type='csv', id=None, order_by=[], batch_metadata={}, batching_regex=re.compile('processed/electricity/prices/.*\\.csv'), connect_options={}, splitter=None, sep=None, delimiter=None, header='infer', names=None, index_col=None, usecols=None, dtype=None, engine=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, skipfooter=0, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=None, skip_blank_lines=True, parse_dates=None, infer_datetime_format=None, keep_date_col=None, date_format=None, dayfirst=False, cache_dates=True, iterator=False, chunksize=None, compression='infer', thousands=None, decimal='.', lineterminator=None, quotechar='"', quoting=0, doublequote=True, escapechar=None, comment=None, encoding=None, encoding_errors='strict', dialect=None, on_bad_lines='error', delim_whitespace=None, low_memory=True, memory_map=False, float_precision=None, storage_options=None, dtype_backend=None), CSVAsset(name='energy_prices_by_zone', type='csv', id=None, order_by=[], batch_metadata={}, batching_regex=re.compile('processed/electricity/prices/(?P<zone>[^/]+)\\.csv'), connect_options={}, splitter=None, sep=None, delimiter=None, header='infer', names=None, index_col=None, usecols=None, dtype=None, engine=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, skipfooter=0, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=None, skip_blank_lines=True, parse_dates=None, infer_datetime_format=None, keep_date_col=None, date_format=None, dayfirst=False, cache_dates=True, iterator=False, chunksize=None, compression='infer', thousands=None, decimal='.', lineterminator=None, quotechar='"', quoting=0, doublequote=True, escapechar=None, comment=None, encoding=None, encoding_errors='strict', dialect=None, on_bad_lines='error', delim_whitespace=None, low_memory=True, memory_map=False, float_precision=None, storage_options=None, dtype_backend=None)], base_directory=PosixPath('../data'), data_context_root_directory=None), data_asset=CSVAsset(name='energy_prices_by_zone', type='csv', id=None, order_by=[], batch_metadata={}, batching_regex=re.compile('processed/electricity/prices/(?P<zone>[^/]+)\\.csv'), connect_options={}, splitter=None, sep=None, delimiter=None, header='infer', names=None, index_col=None, usecols=None, dtype=None, engine=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, skipfooter=0, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=None, skip_blank_lines=True, parse_dates=None, infer_datetime_format=None, keep_date_col=None, date_format=None, dayfirst=False, cache_dates=True, iterator=False, chunksize=None, compression='infer', thousands=None, decimal='.', lineterminator=None, quotechar='"', quoting=0, doublequote=True, escapechar=None, comment=None, encoding=None, encoding_errors='strict', dialect=None, on_bad_lines='error', delim_whitespace=None, low_memory=True, memory_map=False, float_precision=None, storage_options=None, dtype_backend=None), batch_request=BatchRequest(datasource_name='energy_prices', data_asset_name='energy_prices_by_zone', options={'path': 'processed/electricity/prices/BG.csv', 'zone': 'BG'}), data=<great_expectations.execution_engine.pandas_batch_data.PandasBatchData object at 0x7fc7ce486060>, id='energy_prices-energy_prices_by_zone-zone_BG', metadata={'path': 'processed/electricity/prices/BG.csv', 'zone': 'BG'}, batch_markers={'ge_load_time': '20260817T173818.173360Z', 'pandas_data_fingerprint': 'd2abe55048abdcb58f0eb8b304ebd433'}, batch_spec={'path': '../data/processed/electricity/prices/BG.csv', 'reader_method': 'read_csv', 'reader_options': {}}, batch_definition={'datasource_name': 'energy_prices', 'data_connector_name': 'fluent', 'data_asset_name': 'energy_prices_by_zone', 'batch_identifiers': {'path': 'processed/electricity/prices/BG.csv', 'zone': 'BG'}}),
 Batch(datasource=PandasFilesystemDatasource(type='pandas_filesystem', name='energy_prices', id=None, assets=[CSVAsset(name='energy_prices_data', type='csv', id=None, order_by=[], batch_metadata={}, batching_regex=re.compile('processed/electricity/prices/.*\\.csv'), connect_options={}, splitter=None, sep=None, delimiter=None, header='infer', names=None, index_col=None, usecols=None, dtype=None, engine=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, skipfooter=0, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=None, skip_blank_lines=True, parse_dates=None, infer_datetime_format=None, keep_date_col=None, date_format=None, dayfirst=False, cache_dates=True, iterator=False, chunksize=None, compression='infer', thousands=None, decimal='.', lineterminator=None, quotechar='"', quoting=0, doublequote=True, escapechar=None, comment=None, encoding=None, encoding_errors='strict', dialect=None, on_bad_lines='error', delim_whitespace=None, low_memory=True, memory_map=False, float_precision=None, storage_options=None, dtype_backend=None), CSVAsset(name='energy_prices_by_zone', type='csv', id=None, order_by=[], batch_metadata={}, batching_regex=re.compile('processed/electricity/prices/(?P<zone>[^/]+)\\.csv'), connect_options={}, splitter=None, sep=None, delimiter=None, header='infer', names=None, index_col=None, usecols=None, dtype=None, engine=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, skipfooter=0, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=None, skip_blank_lines=True, parse_dates=None, infer_datetime_format=None, keep_date_col=None, date_format=None, dayfirst=False, cache_dates=True, iterator=False, chunksize=None, compression='infer', thousands=None, decimal='.', lineterminator=None, quotechar='"', quoting=0, doublequote=True, escapechar=None, comment=None, encoding=None, encoding_errors='strict', dialect=None, on_bad_lines='error', delim_whitespace=None, low_memory=True, memory_map=False, float_precision=None, storage_options=None, dtype_backend=None)], base_directory=PosixPath('../data'), data_context_root_directory=None), data_asset=CSVAsset(name='energy_prices_by_zone', type='csv', id=None, order_by=[], batch_metadata={}, batching_regex=re.compile('processed/electricity/prices/(?P<zone>[^/]+)\\.csv'), connect_options={}, splitter=None, sep=None, delimiter=None, header='infer', names=None, index_col=None, usecols=None, dtype=None, engine=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, skipfooter=0, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=None, skip_blank_lines=True, parse_dates=None, infer_datetime_format=None, keep_date_col=None, date_format=None, dayfirst=False, cache_dates=True, iterator=False, chunksize=None, compression='infer', thousands=None, decimal='.', lineterminator=None, quotechar='"', quoting=0, doublequote=True, escapechar=None, comment=None, encoding=None, encoding_errors='strict', dialect=None, on_bad_lines='error', delim_whitespace=None, low_memory=True, memory_map=False, float_precision=None, storage_options=None, dtype_backend=None), batch_request=BatchRequest(datasource_name='energy_prices', data_asset_name='energy_prices_by_zone', options={'path': 'processed/electricity/prices/CH.csv', 'zone': 'CH'}), data=<great_expectations.execution_engine.pandas_batch_data.PandasBatchData object at 0x7fc7ce5b1ee0>, id='energy_prices-energy_prices_by_zone-zone_CH', metadata={'path': 'processed/electricity/prices/CH.csv', 'zone': 'CH'}, batch_markers={'ge_load_time': '20260817T173818.212164Z', 'pandas_data_fingerprint': 'b91a7dff7ef6a70c04503fb59974ed96'}, batch_spec={'path': '../data/processed/electricity/prices/CH.csv', 'reader_method': 'read_csv', 'reader_options': {}}, batch_definition={'datasource_name': 'energy_prices', 'data_connector_name': 'fluent', 'data_asset_name': 'energy_prices_by_zone', 'batch_identifiers': {'path': 'processed/electricity/prices/CH.csv', 'zone': 'CH'}}),

In [12]:
batch_request = data_asset.build_batch_request()

validator = context.get_validator(
    batch_request=batch_request,
    expectation_suite_name=expectation_suite_name
)

In [13]:
validator.head()

Calculating Metrics:   0%|          | 0/1 [00:00<?, ?it/s]

,datetime_utc,price,price.1,hour,day_of_week,day,month,year,is_weekend
0,2024-01-01 00:00:00+00:00,0.01,NaN,0,0,1,1,2024,False
1,2024-01-01 01:00:00+00:00,0.05,NaN,1,0,1,1,2024,False
2,2024-01-01 02:00:00+00:00,0.01,NaN,2,0,1,1,2024,False
3,2024-01-01 05:00:00+00:00,0.04,NaN,5,0,1,1,2024,False
4,2024-01-01 06:00:00+00:00,0.01,NaN,6,0,1,1,2024,False

In [14]:
import pandas as pd

test_df = pd.read_csv(
    "../data/processed/electricity/prices/SK.csv"
)

print(test_df.columns.tolist())
print(test_df.head())

['datetime_utc', 'price', 'price.1', 'hour', 'day_of_week', 'day', 'month', 'year', 'is_weekend']
                datetime_utc  price  price.1  hour  day_of_week  day  month  \
0  2024-01-01 00:00:00+00:00   0.01      NaN     0            0    1      1
1  2024-01-01 01:00:00+00:00   0.05      NaN     1            0    1      1
2  2024-01-01 02:00:00+00:00   0.01      NaN     2            0    1      1
3  2024-01-01 05:00:00+00:00   0.04      NaN     5            0    1      1
4  2024-01-01 06:00:00+00:00   0.01      NaN     6            0    1      1

   year  is_weekend
0  2024       False
1  2024       False
2  2024       False
3  2024       False
4  2024       False

In [15]:
batch_request = data_asset.build_batch_request()

validator = context.get_validator(
    batch_request=batch_request,
    expectation_suite_name=expectation_suite_name
)

validator.head()

Calculating Metrics:   0%|          | 0/1 [00:00<?, ?it/s]

,datetime_utc,price,hour,day_of_week,day,month,year,is_weekend
0,2024-01-01 00:00:00+00:00,0.01,0,0,1,1,2024,False
1,2024-01-01 01:00:00+00:00,0.05,1,0,1,1,2024,False
2,2024-01-01 02:00:00+00:00,0.01,2,0,1,1,2024,False
3,2024-01-01 05:00:00+00:00,0.04,5,0,1,1,2024,False
4,2024-01-01 06:00:00+00:00,0.01,6,0,1,1,2024,False

In [16]:
batches = data_asset.get_batch_list_from_batch_request(
    data_asset.build_batch_request()
)

print("Število batchov:", len(batches))

Število batchov: 37

In [17]:
validator.expect_table_columns_to_match_set(
    column_set=[
        "datetime_utc",
        "price",
        "hour",
        "day_of_week",
        "day",
        "month",
        "year",
        "is_weekend",
    ],
    exact_match=True,
)

Calculating Metrics:   0%|          | 0/2 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "observed_value": [
      "datetime_utc",
      "price",
      "hour",
      "day_of_week",
      "day",
      "month",
      "year",
      "is_weekend"
    ]
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [18]:
validator.expect_column_values_to_not_be_null(
    "datetime_utc"
)

validator.expect_column_values_to_be_unique(
    "datetime_utc"
)

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 22976,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [19]:
validator.expect_column_values_to_not_be_null(
    "price"
)

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 22976,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": []
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [20]:
validator.expect_column_values_to_be_between(
    "hour",
    min_value=0,
    max_value=23,
)

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 22976,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [21]:
validator.expect_column_values_to_be_between(
    "day_of_week",
    min_value=0,
    max_value=6,
)

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 22976,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [22]:
validator.expect_column_values_to_be_between(
    "month",
    min_value=1,
    max_value=12,
)

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 22976,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [23]:
validator.expect_column_values_to_be_between(
    "year",
    min_value=2024,
)

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 22976,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [24]:
validator.expect_column_values_to_be_in_set(
    "is_weekend",
    value_set=[True, False],
)

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 22976,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [25]:
context.save_expectation_suite(
    expectation_suite=validator.get_expectation_suite()
)

'/home/urban/Documents/IIS/projekt/gx/expectations/energy_prices_suite.json'

In [26]:
print(
    len(
        validator.get_expectation_suite().expectations
    )
)

9

In [27]:
checkpoint_name = "energy_prices_checkpoint"

checkpoint = context.add_or_update_checkpoint(
    name=checkpoint_name,
    validations=[
        {
            "batch_request": data_asset.build_batch_request(),
            "expectation_suite_name": expectation_suite_name,
        }
    ],
)

In [28]:
checkpoint_result = checkpoint.run()

Calculating Metrics:   0%|          | 0/53 [00:00<?, ?it/s]

In [29]:
print(checkpoint_result["success"])

True